#!/bin/sh
TGZ_DEST="$HOME/shiro.dreamhost.com/scheme/vault/"
MAN_DEST="$HOME/shiro.dreamhost.com/scheme/gauche/man/"
CHANGELOG_DEST="$HOME/shiro.dreamhost.com/scheme/gauche/ChangeLog.Gauche-gtk.txt"

while [ $# -gt 0 ]; do
  case $1 in
    gen) gen=yes; shift;;
    doc) docs=yes; shift ;;
    tgz) tgz=yes; shift ;;
    test) test=yes; shift ;;
    testclean) testclean=yes; shift ;;
    *) echo "DIST [doc][tgz][test][testclean]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  autoconf -I `gauche-config --ac`
fi

if [ "$tgz" = "yes" ]; then
  if [ -f Makefile ]; then make maintainer-clean; fi
  autoconf -I `gauche-config --ac`
  ./configure

  if [ ! -f VERSION ]; then echo "No VERSION; something wrong?"; exit 1; fi
  VERSION=`cat VERSION`

#  (cd doc; make html)
  (cd src; make stubs)
#  escm -o INSTALL INSTALL.esc
#  LANG=ja_JP escm -o INSTALL.eucjp INSTALL.esc
  make distclean

  rm -rf ../Gauche-gtk-$VERSION
  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -print -prune >> DIST_EXCLUDE_X

  mkdir ../Gauche-gtk-$VERSION
  tar cvfX - DIST_EXCLUDE_X . | (cd ../Gauche-gtk-$VERSION; tar xf -)
  (cd ..; tar cvf - Gauche-gtk-$VERSION | gzip -9 > Gauche-gtk-$VERSION.tgz)
#  mv ../Gauche-gtk-$VERSION.tgz $TGZ_DEST
#  cp ChangeLog $CHANGELOG_DEST
fi

