/* src/gtk-config.h.  Generated by configure.  */
/* -*-C-*-
 *
 * Gauche-gtk configuration parmateres
 *
 * $Id: gtk-config.h,v 1.1.1.1 2007/01/13 00:56:57 maruska Exp $
 */

/* Define gauche version */
#define GAUCHE_VERSION "0.8.5"

/* If we use gtkglext, define this */
#define HAVE_GTKGL 1

/* If we use glgd, define this */
/* #undef HAVE_GLGD */

/* If we use glgd-pango, define this */
/* #undef HAVE_GLGD_PANGO */

